"""empty message

Revision ID: 45a72275ae7
Revises: None
Create Date: 2015-07-14 23:25:50.047359

"""

# revision identifiers, used by Alembic.
revision = '45a72275ae7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
